[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/engine.rs"

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
gl = "0.14.0"
glfw = "0.50.0"
cgmath = "0.18.0"
